"use client";
import { useEffect, useState } from "react";

const ADMIN_EMAIL="admin@institutionaltradingacademy.com";
const defaultConfig={heroTitle:"Stop chasing trades.",heroAccent:"Build a trading process.",telegramUrl:"https://t.me/",certificates:[],heroCopy:"Learn market structure, liquidity, risk management and trading psychology through a structured approach designed to help you execute with discipline.",audience:"14K+",experience:"3+",offers:[
{name:"Digital Starter",price:"$5",description:"A practical introduction to structured trading, risk management and psychology.",features:["Trading psychology guide","Risk management framework","Core market-structure concepts","Instant digital access"],cta:"Get the $5 Product",href:"#",featured:false},
{name:"Base Coaching",price:"$147",description:"A structured coaching program for traders who want a repeatable process.",features:["Complete trading framework","Market structure & liquidity","Risk management system","Trading psychology","Community access","Coaching sessions"],cta:"Join Base Coaching",href:"#",featured:true},
{name:"Premium Coaching",price:"$497",description:"High-touch coaching for traders who want deeper feedback and accountability.",features:["Everything in Base","Personalized trade reviews","Direct coaching access","Execution feedback","Advanced accountability"],cta:"Get Premium Coaching",href:"#",featured:false}]};

export default function Admin(){
 const[logged,setLogged]=useState(false),[email,setEmail]=useState(""),[cfg,setCfg]=useState<any>(defaultConfig),[msg,setMsg]=useState("");
 useEffect(()=>{try{const s=localStorage.getItem("itaSiteConfig");if(s)setCfg({...defaultConfig,...JSON.parse(s)});}catch{}},[]);
 const login=(e:any)=>{e.preventDefault();if(email===ADMIN_EMAIL)setLogged(true);else setMsg("Use the configured admin email.");};
 const save=()=>{localStorage.setItem("itaSiteConfig",JSON.stringify(cfg));setMsg("Saved in this browser. Production authentication/database should be added before launch.");};
 const editOffer=(i:number,k:string,v:any)=>setCfg({...cfg,offers:cfg.offers.map((o:any,n:number)=>n===i?{...o,[k]:v}:o)});
 if(!logged)return <main className="admin-page"><div className="admin-card"><div className="eyebrow">ITA ADMIN</div><h1>Admin Panel</h1><p>Development access for configuring the landing page.</p><form onSubmit={login}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} placeholder={ADMIN_EMAIL}/></label><button className="button primary full">Continue</button></form>{msg&&<p className="admin-error">{msg}</p>}<div className="demo-box"><strong>Sample admin email</strong><br/>{ADMIN_EMAIL}<br/><br/>Authentication is intentionally not hard-coded in this prototype.</div><a className="back" href="/">← Back to landing page</a></div></main>;
 return <main className="admin-page"><div className="admin-shell"><div className="admin-head"><div><div className="eyebrow">INSTITUTIONAL TRADING ACADEMY</div><h1>Landing Page Admin</h1><p>Edit page content and Chariow checkout links.</p></div><a className="button ghost" href="/">View site</a></div>
 <section className="admin-section"><h2>Hero</h2><label>Headline<input value={cfg.heroTitle} onChange={e=>setCfg({...cfg,heroTitle:e.target.value})}/></label><label>Accent headline<input value={cfg.heroAccent} onChange={e=>setCfg({...cfg,heroAccent:e.target.value})}/></label><label>Hero description<textarea value={cfg.heroCopy} onChange={e=>setCfg({...cfg,heroCopy:e.target.value})}/></label><div className="admin-grid"><label>Audience<input value={cfg.audience} onChange={e=>setCfg({...cfg,audience:e.target.value})}/></label><label>Experience<input value={cfg.experience} onChange={e=>setCfg({...cfg,experience:e.target.value})}/></label></div></section>
 <section className="admin-section"><h2>Community & Credentials</h2><label>Free Telegram URL<input value={cfg.telegramUrl||""} onChange={e=>setCfg({...cfg,telegramUrl:e.target.value})} placeholder="https://t.me/yourchannel"/></label><p className="security-note">Certificates are currently managed as secure links. A persistent file-upload system will require storage/backend integration before production.</p>{(cfg.certificates||[]).map((c:any,i:number)=><div className="edit-offer" key={i}><h3>Certificate {i+1}</h3><label>Certificate title<input value={c.title} onChange={e=>{const cs=[...(cfg.certificates||[])];cs[i]={...cs[i],title:e.target.value};setCfg({...cfg,certificates:cs})}}/></label><label>Certificate URL<input value={c.url} onChange={e=>{const cs=[...(cfg.certificates||[])];cs[i]={...cs[i],url:e.target.value};setCfg({...cfg,certificates:cs})}} placeholder="https://..."/></label></div>)}<button className="button ghost" type="button" onClick={()=>setCfg({...cfg,certificates:[...(cfg.certificates||[]),{title:"New Certificate",url:""}]})}>+ Add Certificate</button></section><section className="admin-section"><h2>Chariow Offers</h2>{cfg.offers.map((o:any,i:number)=><div className="edit-offer" key={i}><h3>{o.name}</h3><div className="admin-grid"><label>Name<input value={o.name} onChange={e=>editOffer(i,"name",e.target.value)}/></label><label>Price<input value={o.price} onChange={e=>editOffer(i,"price",e.target.value)}/></label></div><label>Description<textarea value={o.description} onChange={e=>editOffer(i,"description",e.target.value)}/></label><label>Chariow checkout/product URL<input value={o.href} onChange={e=>editOffer(i,"href",e.target.value)} placeholder="https://..."/></label><label>Button text<input value={o.cta} onChange={e=>editOffer(i,"cta",e.target.value)}/></label><label>Features (one per line)<textarea value={o.features.join("\n")} onChange={e=>editOffer(i,"features",e.target.value.split("\n"))}/></label></div>)}</section>
 <button className="button primary save-button" onClick={save}>Save changes</button>{msg&&<p className="save-msg">{msg}</p>}<p className="security-note">Prototype only: settings are stored in browser localStorage. Before production, authentication and shared content storage should be moved to a server/database.</p></div></main>
}