"use client";
import { useEffect, useState } from "react";

const defaultConfig={heroTitle:"Stop chasing trades.",heroAccent:"Build a trading process.",telegramUrl:"https://t.me/",certificates:[],heroCopy:"Learn market structure, liquidity, risk management and trading psychology through a structured approach designed to help you execute with discipline.",audience:"14K+",experience:"3+",offers:[
{name:"Digital Starter",price:"$5",description:"A practical introduction to structured trading, risk management and psychology.",features:["Trading psychology guide","Risk management framework","Core market-structure concepts","Instant digital access"],cta:"Get the $5 Product",href:"#",featured:false},
{name:"Base Coaching",price:"$147",description:"A structured coaching program for traders who want a repeatable process.",features:["Complete trading framework","Market structure & liquidity","Risk management system","Trading psychology","Community access","Coaching sessions"],cta:"Join Base Coaching",href:"#",featured:true},
{name:"Premium Coaching",price:"$497",description:"High-touch coaching for traders who want deeper feedback and accountability.",features:["Everything in Base","Personalized trade reviews","Direct coaching access","Execution feedback","Advanced accountability"],cta:"Get Premium Coaching",href:"#",featured:false}]};

export default function Admin(){
 const[logged,setLogged]=useState(false),[email,setEmail]=useState("admin@institutionaltradingacademy.com"),[password,setPassword]=useState(""),[loginMsg,setLoginMsg]=useState(""),[tab,setTab]=useState("dashboard");
 const[cfg,setCfg]=useState<any>(defaultConfig),[customers,setCustomers]=useState<any[]>([]),[stats,setStats]=useState({total:0,consented:0,today:0}),[loading,setLoading]=useState(true),[msg,setMsg]=useState("");
 useEffect(()=>{try{const s=localStorage.getItem("itaSiteConfig");if(s)setCfg({...defaultConfig,...JSON.parse(s)});}catch{};loadCustomers();},[]);
 async function loadCustomers(){
  setLoading(true);const res=await fetch("/api/admin/customers",{cache:"no-store"});
  if(res.ok){const d=await res.json();setLogged(true);setCustomers(d.customers);setStats(d.stats);}else setLogged(false);setLoading(false);
 }
 async function login(e:any){
  e.preventDefault();setLoginMsg("");
  const res=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});
  const d=await res.json();
  if(!res.ok){setLoginMsg(d.error||"Login failed.");return;}
  setLogged(true);setPassword("");loadCustomers();
 }
 async function logout(){await fetch("/api/admin/logout",{method:"POST"});setLogged(false);setCustomers([]);}
 const save=()=>{localStorage.setItem("itaSiteConfig",JSON.stringify(cfg));setMsg("Saved in this browser.");};
 const editOffer=(i:number,k:string,v:any)=>setCfg({...cfg,offers:cfg.offers.map((o:any,n:number)=>n===i?{...o,[k]:v}:o)});
 if(!logged)return <main className="admin-page"><div className="admin-card"><div className="eyebrow">ITA CONTROL CENTER</div><h1>Admin login</h1><p>Secure access to your academy dashboard.</p><form onSubmit={login}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required placeholder="Your admin password"/></label><button className="button primary full">Sign in</button></form>{loginMsg&&<p className="admin-error">{loginMsg}</p>}<a className="back" href="/">← Back to site</a></div></main>;

 return <main className="admin-page"><div className="admin-shell">
  <header className="admin-head"><div><div className="eyebrow">INSTITUTIONAL TRADING ACADEMY</div><h1>Control Center</h1><p>Manage leads, customers, offers and academy content.</p></div><div className="admin-head-actions"><a className="button ghost" href="/">View site</a><button className="button ghost" onClick={logout}>Sign out</button></div></header>
  <nav className="admin-tabs"><button className={tab==="dashboard"?"active":""} onClick={()=>setTab("dashboard")}>Dashboard</button><button className={tab==="customers"?"active":""} onClick={()=>setTab("customers")}>Customers</button><button className={tab==="content"?"active":""} onClick={()=>setTab("content")}>Website Content</button></nav>
  {tab==="dashboard"&&<><div className="admin-stats"><div><span>Total accounts</span><strong>{stats.total}</strong></div><div><span>Marketing consent</span><strong>{stats.consented}</strong></div><div><span>New today</span><strong>{stats.today}</strong></div><div><span>Offers</span><strong>3</strong></div></div><section className="admin-section"><div className="section-row"><div><h2>Recent registrations</h2><p>Latest people who created an ITA account.</p></div><button className="button ghost small-button" onClick={loadCustomers}>Refresh</button></div><CustomerTable rows={customers.slice(0,8)} loading={loading}/></section></>}
  {tab==="customers"&&<section className="admin-section"><div className="section-row"><div><h2>Customers & Leads</h2><p>Contacts collected through the ITA registration system.</p></div><button className="button ghost small-button" onClick={loadCustomers}>Refresh</button></div><CustomerTable rows={customers} loading={loading}/></section>}
  {tab==="content"&&<><section className="admin-section"><h2>Hero</h2><label>Headline<input value={cfg.heroTitle} onChange={e=>setCfg({...cfg,heroTitle:e.target.value})}/></label><label>Accent headline<input value={cfg.heroAccent} onChange={e=>setCfg({...cfg,heroAccent:e.target.value})}/></label><label>Hero description<textarea value={cfg.heroCopy} onChange={e=>setCfg({...cfg,heroCopy:e.target.value})}/></label><div className="admin-grid"><label>Audience<input value={cfg.audience} onChange={e=>setCfg({...cfg,audience:e.target.value})}/></label><label>Experience<input value={cfg.experience} onChange={e=>setCfg({...cfg,experience:e.target.value})}/></label></div></section>
  <section className="admin-section"><h2>Community & Credentials</h2><label>Free Telegram URL<input value={cfg.telegramUrl||""} onChange={e=>setCfg({...cfg,telegramUrl:e.target.value})}/></label><p className="security-note">Certificate links can be added here. Persistent uploads will be added with storage integration.</p>{(cfg.certificates||[]).map((c:any,i:number)=><div className="edit-offer" key={i}><h3>Certificate {i+1}</h3><label>Title<input value={c.title} onChange={e=>{const cs=[...cfg.certificates];cs[i]={...cs[i],title:e.target.value};setCfg({...cfg,certificates:cs})}}/></label><label>URL<input value={c.url} onChange={e=>{const cs=[...cfg.certificates];cs[i]={...cs[i],url:e.target.value};setCfg({...cfg,certificates:cs})}}/></label></div>)}<button className="button ghost" onClick={()=>setCfg({...cfg,certificates:[...(cfg.certificates||[]),{title:"New Certificate",url:""}]})}>+ Add Certificate</button></section>
  <section className="admin-section"><h2>Chariow Offers</h2>{cfg.offers.map((o:any,i:number)=><div className="edit-offer" key={i}><h3>{o.name}</h3><div className="admin-grid"><label>Name<input value={o.name} onChange={e=>editOffer(i,"name",e.target.value)}/></label><label>Price<input value={o.price} onChange={e=>editOffer(i,"price",e.target.value)}/></label></div><label>Description<textarea value={o.description} onChange={e=>editOffer(i,"description",e.target.value)}/></label><label>Chariow URL<input value={o.href} onChange={e=>editOffer(i,"href",e.target.value)}/></label><label>Button text<input value={o.cta} onChange={e=>editOffer(i,"cta",e.target.value)}/></label><label>Features<textarea value={o.features.join("\n")} onChange={e=>editOffer(i,"features",e.target.value.split("\n"))}/></label></div>)}</section><button className="button primary save-button" onClick={save}>Save content</button>{msg&&<p className="save-msg">{msg}</p></>}
 </div></main>;
}

function CustomerTable({rows,loading}:{rows:any[],loading:boolean}){
 if(loading)return <div className="empty-state">Loading customers…</div>;
 if(!rows.length)return <div className="empty-state">No registrations yet. Your first account will appear here.</div>;
 return <div className="customer-table-wrap"><table className="customer-table"><thead><tr><th>Name</th><th>Email</th><th>Phone</th><th>Consent</th><th>Joined</th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td><strong>{c.name}</strong></td><td>{c.email}</td><td>{c.phone||"—"}</td><td><span className={c.marketing_consent?"consent-badge":"no-consent"}>{c.marketing_consent?"Yes":"No"}</span></td><td>{new Date(c.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div>
}